name: orthrus
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - sage-proteomics
  - pip
  - pip:
      - biopython
      - mokapot
      - instanovo
      - casanovo
      - pridepy
      - pre_commit
